# Generated by Django 4.2.4 on 2023-08-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstoremodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookstoremodel',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='bookstoremodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookstoremodel',
            name='first_pub',
        ),
        migrations.RemoveField(
            model_name='bookstoremodel',
            name='last_pub',
        ),
        migrations.AddField(
            model_name='bookstoremodel',
            name='taskDescription',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='bookstoremodel',
            name='taskTitle',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
